// import type { Metadata } from 'next'
// import { Inter } from 'next/font/google'
// import './globals.css'
// import React from 'react';
// import { ChakraProvider } from '@chakra-ui/react';
// import Header from './components/Header';

// const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode
// }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   )
// }

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import React from 'react';
import { ChakraProvider } from '@chakra-ui/react';
import Header from './components/Header'; // Make sure the path is correct
import { CSPostHogProvider } from './providers'
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Chat with any Youtube Channel using AI',
  description: 'Chat with any Youtube Channel using AI',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        {/* Ensure you have a Head component for meta tags, like title and description */}
        {/* <style>{inter.style}</style> */}
      </head>
      <CSPostHogProvider>
        <body className={inter.className}>
          <ChakraProvider>
            {/* Header component included here, it will be displayed on every page */}
            <Header />
            {/* This is where the content of your pages will be rendered */}
            <main style={{ paddingTop: '4rem' }}>{children}</main>
          </ChakraProvider>
        </body>
      </CSPostHogProvider>
    </html>
  );
}
